### ISSUE TITLE
Calibración 

### ISSUE THREAD

**Issue by son0p** [unloquer/AQA#13]
Para comparar la medición del sensor laser con el homologado del SIATA tenemos unas mediciones a pocos metros de la estación de la Y (zona del tesoro) :

- 2017-05-18 a las 10:01, PM2.5 : 40
- 2017-05-18 a las 14:23, PM2.5 : 22 

Alguien puede ayudar a evaluar los datos de esa estación ese día a esas horas y comparar las mediciones para tener una aproximación al margen de error que estamos viviendo.

**Comment by estebanz01** [comment]
¿Qué metodología se tiene en mente para identificar dicha diferencia? Estaba pensando realizar una comparación de varianza respecto a lo que mide el SIATA o también un t-test comparando ambas distribuciones de contaminación (y suponiendo que las particulas tienen un comportamiento normal).

**Comment by son0p** [comment]
Una muy básica, mirar las mediciones cercanas a alguna estación  del SIATA
y comparar la medida con la reportada por el SIATA a esa misma hora ese día.

Luego podríamos pedir al SIATA que ponga un display con  la medición del
instante en alguna de las estaciones y uno de se para ahí con su sensor y
mira las variaciones.

**Comment by son0p** [comment]
SIATA ofrece ayuda en la calibración de los sensores dejando un sensor por algunos días junto a una de las estaciones calibradas.

**Comment by son0p** [comment]
Ya se están calibrando en la estación de la Torre del Ajedrez (S.I.A.T.A)
