### ISSUE TITLE
Errores en  la altura que reporta el GPS

### ISSUE THREAD

**Issue by son0p** [unloquer/AQA#18]
@josenobile señala altitudes sospechosas en la trama de datos:

lat,lng,date,hour,altitude,course,speed,humidity,temperature,pm1,pm25,pm10
6.263632,-75.597555,5/11/2017,06:13:41.00,1526.7,338.67,0.0,33.0,28.0,11,16,16
6.263632,-75.597555,5/11/2017,06:13:46.00,1526.7,338.67,0.0,32.0,29.0,10,15,15
6.263632,-75.597555,5/11/2017,06:13:52.00,1526.7,338.67,0.0,32.0,29.0,10,15,15
6.263632,-75.597555,5/11/2017,06:13:57.00,1526.7,338.67,0.0,32.0,29.0,10,15,15
6.2499,-75.593618,5/11/2017,22:59:34.00,150.6,103.42,28.54,38.0,23.0,53,75,82
6.249803,-75.593328,5/11/2017,22:59:39.00,152.7,118.22,25.0,38.0,23.0,53,75,82
6.249647,-75.593075,5/11/2017,22:59:45.00,155.0,135.6,18.82,38.0,23.0,53,75,82
6.249367,-75.592937,5/11/2017,22:59:50.00,157.7,156.37,23.37,38.0,23.0,53,75,82
6.249087,-75.592778,5/11/2017,22:59:56.00,159.6,149.09,20.67,38.0,23.0,53,75,82
6.248748,-75.592612,5/11/2017,23:00:02.00,155.9,149.59,20.52,38.0,23.0,53,75,82
6.248477,-75.592462,5/11/2017,23:00:08.00,157.8,148.75,18.56,38.0,23.0,41,55,61

Hay momentos donde se pasa de por ejemplo 1526 metros a 150 metros en la calle San Juan de Medellín.

**Comment by josenobile** [comment]
Los GPS reportan la precision, este dato puede usarse para descartar datos con muy baja precision.

**Comment by julibeth** [comment]
Medellín se encuentra 1.300 y 2.800 metros sobre el nivel del mar. Por lo visto hay casos que la altura no parece errada sino divida entre 10. Ejm:   150.6= 1506/10

**Comment by josenobile** [comment]
Es correcto la apreciación de @julibeth Aunque eso indicaría el GPS tiene bugs, ya que no hace entrega consistente de los datos en cuanto a su representación.

**Comment by son0p** [comment]
Vamos a cerrar este issue por que consideramos que los errores de las mediciones de altura se deben a los momentos en que el GPS no esta bien localizado.
